import QtQuick 2.0
import QtQuick.Controls 1.4
import QtQuick.Controls.Styles 1.4
Rectangle{
    id:storage;

    width:parent.width; height:parent.height; color:"#f0f0f0";
    anchors{left:parent.left;top:parent.top;}
    state:"hide";
    //border{color:"lime";width:10}

    ScrollView{
        id:scrollview_storage;

        anchors.fill:parent;
        Rectangle{
            id:emptylayer;

            width:parent.width; height:2000; color:"transparent";

            Text{
                id:title_chanpin;

                text:"产品";
                anchors{top:parent.top;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"三星 SSD 850 EVO 120GB（固态硬盘）";
                anchors{top:title_chanpin.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_rongliang;

                text:"固件";
                anchors{top:title_chanpin.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"CC45";
                anchors{top:title_rongliang.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_xingzhuangtezheng;

                text:"序列号";
                anchors{top:title_rongliang.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"Z4Y19VCY";
                anchors{top:title_xingzhuangtezheng.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_cache;

                text:"接口";
                anchors{top:title_xingzhuangtezheng.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"Serial ATA";
                anchors{top:title_cache.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_diskused;

                text:"传输模式";
                anchors{top:title_cache.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"SATA/600";
                anchors{top:title_diskused.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_firm;

                text:"卷标";
                anchors{top:title_diskused.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"E: J:";
                anchors{top:title_firm.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_jiekou;

                text:"标准";
                anchors{top:title_firm.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"| ---[001Fh]";
                anchors{top:title_jiekou.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_transferrate;

                text:"支持的特征";
                anchors{top:title_jiekou.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"S.M.A.R.T., 48bit LBA, APM, AAM, NCQ, TRIM";
                anchors{top:title_transferrate.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_charactor;

                text:"缓存大小";
                anchors{top:title_transferrate.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"未知";
                anchors{top:title_charactor.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_maincontroller;

                text:"NV缓存大小";
                anchors{top:title_charactor.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"---";
                anchors{top:title_maincontroller.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_flashtype;

                text:"转动率";
                anchors{top:title_maincontroller.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"7200 RPM";
                anchors{top:title_flashtype.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_sequentialread;

                text:"使用周期";
                anchors{top:title_flashtype.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"1021周期";
                anchors{top:title_sequentialread.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_sequentialwrite;

                text:"使用时间";
                anchors{top:title_sequentialread.bottom;topMargin:20;left:parent.left;leftMargin:15;}
            }
            Text{
                text:"1617小时";
                anchors{top:title_sequentialwrite.top;left:parent.right;leftMargin:100;}
            }
            Text{
                id:title_chosed;

                anchors{top:title_sequentialwrite.bottom;topMargin:20;left:parent.left;leftMargin:40;}
                text:"选择";
            }
            BasicComboBox{
                id:combo_chosed_identify;

                currentIndex:1;
                choosedItem:ListModel{
                    //id:list_chosed;
                    ListElement{text:"disk 1";}
                    ListElement{text:"disk 2";}
                    ListElement{text:"disk 3";}
                }
                width:80
                anchors{verticalCenter:title_chosed.verticalCenter;left:title_chosed.right;leftMargin:5;}
            }
            BasicTableView{
                id:identify_table;

                width:40*identify_table.columnCount; height:identify_table.rowCount*16+1;
                anchors{top:combo_chosed_identify.bottom;topMargin:20;left:parent.left;leftMargin:50;}

                model:ListModel{
                    ListElement{
                        col1:"0";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"00";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"01";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"02";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"03";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"04";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"05";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"06";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"07";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"08";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"09";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0A";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0B";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0C";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0D";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0E";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0F";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                }
                Component.onCompleted: identify_table.createTableViewColumn([["col1","col2","col3","col4","col5","col6","col7","col8","col9","col10","col11","col12","col13","col14","col15","col16","col17"],//
                                                                             ["Col1","Col2","Col3","Col4","Col5","Col6","Col7","Col8","Col9","Col10","Col11","Col12","Col13","Col14","Col15","Col16","Col17"],//
                                                                             [40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40]]);
            }
            BasicComboBox{
                id:combo_chosed_RW;

                currentIndex:1;
                choosedItem:ListModel{
                    ListElement{text:"disk 1";}
                    ListElement{text:"disk 2";}
                    ListElement{text:"disk 3";}
                }
                width:80;
                anchors{top:identify_table.bottom;topMargin:20;left:title_chosed.right;leftMargin:5;}
            }
            Text{
                id:title_LBA;

                text:"LBA";
                anchors{top:combo_chosed_RW.top;left:combo_chosed_RW.right;leftMargin:50;}
            }
            TextField{
                id:input_LBA;

                width:100; height:Text.contentHeight;
                anchors{top:title_LBA.top;topMargin:-7;left:title_LBA.right;leftMargin:5;}
            }

            BasicTableView{
                id:table_RW;

                width:40*table_RW.columnCount; height:table_RW.rowCount*16+1;
                anchors{top:combo_chosed_RW.bottom;topMargin:20;left:parent.left;leftMargin:50;}
                model:ListModel{
                    ListElement{
                        col1:"0";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"00";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"01";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"02";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"03";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"04";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"05";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"06";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"07";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"08";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"09";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0A";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0B";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0C";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0D";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0E";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                    ListElement{
                        col1:"0F";
                        col2:"00";
                        col3:"01";
                        col4:"02";
                        col5:"03";
                        col6:"04";
                        col7:"05";
                        col8:"06";
                        col9:"07";
                        col10:"08";
                        col11:"09";
                        col12:"0A";
                        col13:"0B";
                        col14:"0C";
                        col15:"0D";
                        col16:"0E";
                        col17:"0F";
                    }
                }
                Component.onCompleted: table_RW.createTableViewColumn([["col1","col2","col3","col4","col5","col6","col7","col8","col9","col10","col11","col12","col13","col14","col15","col16","col17"],//
                                                                             ["Col1","Col2","Col3","Col4","Col5","Col6","Col7","Col8","Col9","Col10","Col11","Col12","Col13","Col14","Col15","Col16","Col17"],//
                                                                             [40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40]]);

            }
            /*
            Rectangle{
                id:tree_usb;

                width:700; height:600;color:"transparent"
                anchors{top:table_RW.bottom;topMargin:20;left:parent.left;leftMargin:50;}

                BasicTreeView{
                    anchors.fill:parent;
                    model:ListModel {
                        id: treemodel;

                        ListElement { text: "Level 1, Node 1" ;}
                        ListElement {
                            text: "Level 1, Node 2";
                            elements: [
                                ListElement { text: "Level 2, Node 1";
                                    elements: [
                                        ListElement { text: "Level 3, Node 1" ;}
                                    ]
                                },
                                ListElement { text: "Level 2, Node 2"; }
                            ]
                        }
                        ListElement { text: "Level 1, Node 3"; }
                    }
                }
            }
*/
            ListView{
                id:usb_list
                width:contentWidth;height:contentHeight
                anchors{top:table_RW.bottom;topMargin:20;left:parent.left;leftMargin:20}
                spacing:10
                model:ListModel{
                    ListElement{
                        title:"USB";
                        content:"";
                    }
                    ListElement{
                        title:"Version";
                        content:"A08";
                    }
                    ListElement{
                        title:"Date";
                        content:"04/16/2014";
                    }
                }
                delegate:Text{
                    text:title+"   "+content;
                }
            }
            BasicTopology{
                id:usb_topo
                anchors{top:usb_list.bottom;topMargin:20;left:parent.left;leftMargin:50}
                model:ListModel{
                    ListElement{name:"Standard Enhanced PCI to USB Host Controller"}
                    ListElement{name:"RootHub"}
                    ListElement{name:"[Port1]NodeviceConnected"}
                    ListElement{name:"[Port2]NodeviceConnected"}
                    ListElement{name:"[Port3]NodeviceConnected"}
                    ListElement{name:"[Port4]NodeviceConnected"}
                    ListElement{name:"[Port5]NodeviceConnected"}
                    ListElement{name:"[Port6]NodeviceConnected"}
                    ListElement{name:"[Port7]NodeviceConnected"}
                    ListElement{name:"[Port8]NodeviceConnected"}
                    ListElement{name:"Standard Enhanced PCI to USB Host Controller"}
                    ListElement{name:"RootHub"}
                    ListElement{name:"[Port1]NodeviceConnected"}
                    ListElement{name:"[Port2]NodeviceConnected"}
                    ListElement{name:"[Port3]NodeviceConnected"}
                    ListElement{name:"[Port4]NodeviceConnected"}
                    ListElement{name:"[Port5]NodeviceConnected"}
                    ListElement{name:"[Port6]NodeviceConnected"}
                }
            }
        }
    }

    Component.onCompleted: {
        //console.log("storage's state is",storage.state);
    }
    states:
    [
        State
        {
            name:"active";
            PropertyChanges
            {
                target: storage;
                //x:parent.x;
                //anchors.left:parent.left;
                visible:true;
            }

        },
        State
        {
            name:"hide";
            PropertyChanges
            {
                target: storage;
                //x:maincontent.x + 2*width;
                //anchors.left:parent.right;
                visible:false;
            }
        }

    ]

    transitions:Transition
    {
        PropertyAnimation
        {
            property:"visible";
            duration:100;
            easing.type: Easing.OutBounce;
            easing.amplitude: 0.1;
        }
    }
}
